# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e600f836c79bb6357ef7dbb21eb6fa95796ac0de01f31dd253132b8bd760c6457e6d37466b30498a1e1a2427d8ea83680821b84d3c35f9dcd17bde8b3548aef7

test:
  secret_key_base: c14d12d94d19aec10e881fe3b8ed0dd7182286e6b5b77f23d9568d0530dd35bfdd6fc6743469136183d88c2a721835b85fb8f9aefc484797f8adc3f5732c87d8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
